### ISSUE TITLE
Change repo's 'crystal-language' topic to 'crystal'

### ISSUE THREAD

**Issue by matiasgarciaisaia** [Angarsk8/kemal-react-pg-chat#1]
The Crystal community has somewhat decided to [use `crystal` as the language's topic](https://github.com/search?utf8=✓&q=topic%3Acrystal&type=Repositories).

To avoid fragmentation in the community, please change the `crystal-language` topic, that only has ~28 repositories at the moment, to `crystal`.

Any contributor can change it from the repo's homepage.

See crystal-lang/crystal#4241 for more context.

Thank you very much :)

**Comment by matiasgarciaisaia** [comment]
We're now down to just 9 repos wrongly-tagged - if you can take just a moment to fix this, we're almost there :)

Thank you @Angarsk8, and apologies for the noise!

**Comment by Angarsk8** [comment]
@matiasgarciaisaia done!
